name: Build and Push Docker Images

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      build_tag:
        required: true
        type: string
      build_contexts:
        required: true
        type: string  # Accepting a string that can be split into multiple contexts

env:
  REGISTRY: ghcr.io

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ inputs.image_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:mod/${{ inputs.image_name }}"
          build-contexts: ${{ inputs.build_contexts }}  # Using the input for build contexts
          build-args: |
            "BBB_BUILD_TAG=${{ inputs.build_tag }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ inputs.image_name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
