---
name: Build and Push Docker Images
on:
  push:
    branches:
      - "**"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:mod/apps-akka"
          build-args: |
            "BBB_BUILD_TAG=v3.0.x-release--2024-08-30-014114"
          additional_contexts:
            - src-web=./repos/bigbluebutton/bigbluebutton-web
            - src-common-message=./repos/bigbluebutton/bbb-common-message
            - src-common-web=./repos/bigbluebutton/bbb-common-web

          push: true
          tags: latest/bbb-akka-apps:latest
