---
name: Build and Push Docker Images
on:
  push:
    branches:
      - "**"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:mod/apps-akka"
          build-contexts: |
            "src-common-message=./repos/bigbluebutton/bbb-common-message"
            "src-apps-akka=./repos/bigbluebutton/akka-bbb-apps"
            "src-config=./repos/bigbluebutton/bigbluebutton-html5/private/config/"
          build-args: |
            "BBB_BUILD_TAG=v3.0.x-release--2024-08-30-014114"
          push: true
          tags: latest/bbb-akka-apps:latest
